/**
 * Spw Parser
 *
 * A generator-based parser for the Spw language.
 * All parsing operations yield ParseEvent objects for unified logging and debugging.
 *
 * @spw:portable:seed - No DOM or app-specific imports allowed
 */

// Core types
export type {
  Position,
  Span,
  Brand,
  Token,
  IdentifierTokenData,
  TokenType,
  OperatorKind,
  ModifierKind,
  ConnectorKind,
  ContainerKind,
  CouplingKind,
  PairedBoundaryKind,
  CouplingForm,
  BoundarySide,
  CouplingOccupancy,
  CouplingPayload,
  EmptyBoundaryPayload,
  InhabitedBoundaryPayload,
  ActPlacement,
  OperatorCouplingPort,
  BoundaryCouplingPort,
  CouplingPort,
  CouplingDescriptor,
  OperatorCouplingDescriptor,
  BoundaryCouplingDescriptor,
  CouplingFrame,
  OperatorCouplingFrame,
  BoundaryCouplingFrame,
  BoundarySurfaceCoordinate,
  CouplingProfileStatus,
  CouplingDimensionValueType,
  CouplingDimensionDefinition,
  CouplingPortSemantics,
  CouplingDynamicsDefinition,
  CouplingKindSemantics,
  CouplingSemanticsProfile,
  CouplingProfileIssue,
  CouplingSemanticsProjection,
  ParseEvent,
  ParseEventType,
  TokenEventData,
  EnterEventData,
  ExitEventData,
  MatchEventData,
  BacktrackEventData,
  ErrorEventData,
  ASTNode,
  ASTNodeType,
  SeedNode,
  SeedExpressionNode,
  ExpressionNode,
  OperationNode,
  ModifierChainNode,
  ScopeNode,
  FrameNode,
  BodyNode,
  SequenceNode,
  ReferenceNode,
  LiteralNode,
  IdentifierNode,
  AnnotationNode,
  ConditionNode,
  ParameterNode,
  ProseNode,
  ProseChunkNode,
  CapsuleNode,
  StreamNode,
  NRangeNode,
  MatchNode,
  MatchArmNode,
  WildcardNode,
  SpreadNode,
  PatternNode,
  ParseGenerator,
  ParseResult,
  ParseContextMode,
  ParserOptions,
  LexProfile,
  LexOptions,
  LexOutput,
  GapClass,
  TokenGap,
  ParseEventPolicy,
  ParseEventCounts,
} from './types'

export { DEFAULT_OPTIONS, GAP_CLASSES, PARSE_EVENT_POLICIES, retainsParseEvent } from './types'
export { isSignificantToken, significantTokens } from './types'
export { castToBrand, $register, $frame, $domain, $layer, RegisterId, FrameId, DomainId, LayerId } from './types'

// Lexer
export {
  lex,
  tokenize,
  DEFAULT_LEX_PROFILE,
  PROSE_LEX_PROFILE,
  registerLexProfile,
  resolveLexProfile,
  getLexProfile,
  listLexProfiles,
  buildOperatorMap,
  buildConnectorMap,
  appositionParts,
  classifyGap,
  classifyTokenGaps,
} from './lexer'
export type { AppositionParts } from './lexer'

// Combinators
export type { TokenStream, Parser } from './combinators'
export {
  createTokenStream,
  sequence,
  choice,
  many,
  many1,
  optional,
  map,
  sepBy,
  between,
  lazy,
  named,
  token,
} from './combinators'

// Grammar
export {
  seedNode,
  expressionNode,
  operationNode,
  scopeNode,
  frameNode,
  bodyNode,
  sequenceNode,
  referenceNode,
  literalNode,
  annotationNode,
  modifierChain,
  parameterNode,
} from './grammar'

// Parser
export type {
  ParseOutput,
  ParseCompletenessReceipt,
  ParseExpectedRootKind,
  LogFormatter,
  TraceNode,
  SourceProductDepth,
  SourceProductIdentity,
  SourceProductProfile,
  SourceProductDiagnostics,
  SourceProductEvents,
  SourceTokensData,
  SourceStructureData,
  SourceStructureCompleteness,
  SourceTraceData,
  SourceTokensProduct,
  SourceStructureProduct,
  SourceTraceProduct,
  SourceProduct,
  SourceProductObserver,
  SourceProductOptions,
  SourceProductResult,
} from './parser'
export {
  parse,
  produceSourceProducts,
  SOURCE_PRODUCT_DEPTHS,
  SOURCE_PRODUCT_IDS,
  parseExpression,
  parseStream,
  parseWithLog,
  textFormatter,
  jsonFormatter,
  compactFormatter,
  filterEvents,
  extractTokens,
  extractErrors,
  buildTrace,
  printAST,
} from './parser'

// Instrumentation
export type {
  InstrumentationHooks,
  ASTVisitor,
  AuditItem,
  ASTAuditResult,
  RuleCoverage,
  CoverageReport,
  TimingMetrics,
  RuleTiming,
  EventFilter,
  EventSubscriber,
} from './instrumentation'

export {
  noopHooks,
  createHooks,
  combineHooks,
  processEvent,
  walkAST,
  getNodeChildren,
  findNodes,
  getNodePath,
  getMaxDepth,
  countNodeTypes,
  auditAST,
  CoverageCollector,
  createCoverageHooks,
  MetricsCollector,
  createMetricsHooks,
  EventStream,
  eventFilters,
  createStreamHooks,
} from './instrumentation'

// Canonicalization, differentials, mutation automata, topography probes
export {
  canonicalize,
  hashString,
  reflowProseBlocks,
  wrapWords,
  isProseCommentLine,
  isSlashLineComment,
  migrateSlashCommentsToHash,
  resolveFormatProfile,
  FORMAT_PROFILES,
  readAuthorityDeclarations,
  reconcileAuthority,
  AUTHORITY_FACETS,
  readMassDeclarations,
  measureMass,
  bootstrapMeasureRegistry,
  loadMeasureContextFromSpw,
  resolveFamily,
  reconcileMetric,
  reconcileFamily,
  contextForFamily,
  MASS_FAMILY,
  defaultScheme,
  CORE_SNIPPETS,
  getSnippet,
  listSnippets,
  hydrateSnippet,
  toVscodeSnippets,
  formatVscodeSnippetsJson,
  parseBindings,
  snippetSource,
  type SnippetFamily,
  type SpwSnippet,
  type SnippetBindings,
  type HydrateResult,
  reconcileMass,
  applyMassCorrections,
  MEASURABLE_KEYS,
  formatPulses,
  compareFormatProfiles,
  diffLines,
  FORMAT_CAPABILITIES,
  applyEdits,
  differentialFromSources,
  EVIDENCE_BASES,
  EVIDENCE_DOMAINS,
  EVIDENCE_ROLES,
  runMutationAutomata,
  planMutation,
  collectPlannedEdits,
  resolveMutationRules,
  BUILTIN_MUTATION_RULES,
  MUTATION_PROFILES,
  applyEquivScriptTransforms,
  mutationRulesAsSequenceContext,
  probeMutationTopography,
  snapshotTopography,
  topographyDelta,
  extractBraceProjection,
  braceProjectionDelta,
  classifyMutationUsefulness,
  APPOSITION_SCAN_VERSION,
  scanAppositions,
  appositionSpectrum,
  appositionMasksEqual,
  diffAppositionLattices,
  type AppositionSpan,
  type AppositionCell,
  type AppositionLattice,
  type AppositionSpectrum,
  type AppositionLatticeDelta,
  type ScanAppositionsOptions,
  formatSpwCard,
  formatSpwCards,
  facet,
  STENCIL_VERSION,
  STENCIL_SCHEMA,
  buildStencilMask,
  cutStencil,
  gateStencilMask,
  stencilToAutomataConfig,
  applyStencil,
  formatStencilSpw,
  type StencilMask,
  type Stencil,
  type StencilMaskMode,
  type StencilMaskGate,
  COMPOSITION_FORM_VERSION,
  recognizeCompositionSequence,
  recognizeCompositionSource,
  compositionToProduct,
  formatCompositionSpw,
  hostLabel,
  actBodySketch,
  formatPopulationSpw,
  formatTopographySpw,
  formatCorpusProductSpw,
  type CompositionKind,
  type ConceptualProbeForm,
  type ActConsequenceForm,
  type CompositionForm,
  type SpwFacet,
  type SpwGroup,
  type SpwCardPart,
  type SpwFacetValue,
  type FormatSpwCardOptions,
  CHANGE_REPORT_VERSION,
  compareLex,
  compareAst,
  buildChangeReport,
  formatChangeReportSpw,
  type LexOpKind,
  type LexTokenKey,
  type LexOp,
  type LexChangeReport,
  type AstChangeReport,
  type ChangeReport,
  NEST_PATH_VERSION,
  NEST_PATH_ALPHABET,
  scanNestPaths,
  nestPathDelta,
  nestPathSpectrum,
  formatNestPathSpw,
  type NestPathKind,
  type NestPathGlyph,
  type NestPathNode,
  type NestPathLattice,
  type NestPathDelta,
  PATCH_VERSION,
  PATCH_SCHEMA,
  PATCH_PRODUCER,
  selectionFromSource,
  buildPatch,
  buildPatchFromEdits,
  filterEditsForSelection,
  applyPatch,
  applyPatchToFiles,
  PatchMemoryBank,
  formatPatchSpw,
  type PatchStore,
  type ApplyTargetKind,
  type AstSelection,
  type PatchNarrative,
  type Patch,
  type BuildPatchOptions,
  type ApplyPatchResult,
  type FilePatchTarget,
  inspectGeometry,
  formatGeometryReport,
  transformEdit,
  transformEditList,
  foldEdits,
  foldTransforms,
  composeEditLists,
  composeSequence,
  matrixFromVectors,
  matrixByStratum,
  matrixTranspose,
  formatMatrix,
  vectorMagnitude,
  runOperationalSequence,
  OPERATIONAL_SEQUENCES,
  BOUNDARY_LADDERS,
  OPERATOR_LADDERS,
  BOUNDARY_AXIS_IMPLICATIONS,
  FORM_LADDER_PROFILE,
  boundaryLadder,
  operatorLadder,
  listBoundaryLadders,
  listOperatorLadders,
  listFormLadders,
  probeFormLadder,
  probeBoundaryLadder,
  probeOperatorLadder,
  resolveLadderQuery,
  formatBoundaryAxisTable,
  formatAllLadderNotations,
  operatorLadderTable,
  boundaryLadderTable,
  implicationsForBoundary,
  MOBILITY_RULES,
  REFERENCE_PROGRESSIONS,
  HIGHER_ORDER_FORMS,
  FORM_GEOMETRY_PROFILE,
  FORM_MOBILITY_APPLICATION_PROFILE,
  mobilityRule,
  rulesFrom,
  rulesTo,
  rulesByMotion,
  rulesByStatus,
  applyMobilityRule,
  findNodeAtOffset,
  findNodePathAtOffset,
  positionToOffset,
  offsetToPosition,
  resolveLabelPosition,
  resolveLabelContext,
  isFormLabel,
  walkReferenceProgression,
  runHigherOrderForm,
  formatSiteGraph,
  formatHigherOrderForms,
  formatMobilityRules,
  computationalRuleIds,
  labelSiteGraph,
  contourFormLadder,
  reduceFormContour,
  expandFormContour,
  restoreFormContour,
  formatFormContour,
  contentHash,
  parseRangeFragment,
  splitPathFragment,
  spanToOffsets,
  resolveRange,
  planSpanTransform,
  applyRangePlan,
  formatRangePlan,
  INDEX_PRESETS,
  INDEX_TRADEOFFS,
  resolveIndexConfig,
  applyDialectIndexBias,
  type CanonicalOptions,
  type CanonicalResult,
  type FormatProfileId,
  type AuthorityKind,
  type AuthorityClaim,
  type AuthorityDeclaration,
  type ObservedAuthority,
  type AuthorityVerdict,
  type AuthorityFinding,
  type MassDeclaration,
  type MeasuredMass,
  type MassReconciliation,
  type MassVerdict,
  type MeasurableKey,
  type DeclaredMeasure,
  type FormatCapability,
  type FormatPulse,
  type FormatPulseSequence,
  type ProfileComparison,
  type DiffLine,
  type SourceEdit,
  type SourceDifferential,
  type MutationVector,
  type MutationAutomataConfig,
  type MutationRunResult,
  type MutationProfileId,
  type MutationRule,
  type DerivedEvidenceContribution,
  type DerivedEvidenceProvenance,
  type EvidenceArtifactRef,
  type EvidenceBasis,
  type EvidenceContribution,
  type EvidenceDomain,
  type EvidenceMethod,
  type EvidenceProducer,
  type EvidenceReporter,
  type EvidenceRole,
  type EvidenceUncertainty,
  type EffectGrade,
  type ObservedEvidenceContribution,
  type ObservedEvidenceProvenance,
  type ReportedEvidenceContribution,
  type ReportedEvidenceProvenance,
  type TopographySnapshot,
  type TopographyDelta,
  type TopographyMutationProbe,
  type ParseHealth,
  type PairedContainerCounts,
  type MutationMatrix,
  type LabeledMatrix,
  type TransposedMutationMatrix,
  type OperationalSequence,
  type SequenceRunResult,
  type OperatorLadder,
  type ResolvedFormLadder,
  type BoundaryLadder,
  type FormLadder,
  type FormLadderProbe,
  type OperatorLadderProbe,
  type EnrichmentRole,
  type LadderStep,
  type FormAxis,
  type BoundaryLadderId,
  type LabelSite,
  type LiminalShape,
  type MobilityRule,
  type MobilityApplication,
  type MobilityApplicationReceipt,
  type HigherOrderForm,
  type ReferenceProgression,
  type LabelPosition,
  type FormContourView,
  type FormContourEvidence,
  type FormContourPoint,
  type FormContourDimensions,
  type FormContour,
  type FormReductionPolicy,
  type FormContourReduction,
  type FormContourExpansion,
  type GeometryReport,
  type OperatorGeometryEntry,
  type BraceNestingStats,
  scanFlowProtocol,
  formatFlowProtocolSummary,
  type FlowRole,
  type FlowFixity,
  type FlowUnit,
  type FlowProtocolModule,
  detectGeometricResonances,
  buildResonanceContext,
  runResonanceDetectors,
  compileGeometryBytecode,
  bytecodeOpSimilarity,
  buildGeometryField,
  resolveWeightScheme,
  formatResonanceSummary,
  formatGeometryFieldSummary,
  formatResonanceAsSpw,
  formatGeometryFieldAsSpw,
  DEFAULT_RESONANCE_DETECTORS,
  WEIGHT_SCHEME_DEFAULT,
  WEIGHT_SCHEME_AGENT,
  WEIGHT_SCHEME_THRIFT,
  WEIGHT_SCHEMES,
  type GeometricResonanceType,
  type GeometricResonance,
  type GeometricResonanceReport,
  type GeometryBytecode,
  type ResonanceDetectionContext,
  type ResonanceDetector,
  type ResonanceWeightScheme,
  type ResonanceFeatureGains,
  type GeometrySurfaceCard,
  type GeometryStrand,
  type GeometryField,
  type BuildGeometryFieldOptions,
  type EvalScheme,
  type MeasureFamilyDef,
  type MeasureAlgorithmDef,
  type MeasureContextRegistry,
  type AttentionalScope,
  type PerceptivePlane,
  type RepresentationalForm,
  type RangeEncoding,
  type SourcePosition,
  type SourceSpan,
  type ResolvedRange,
  type SpanTransformId,
  type SpanTransformOptions,
  type RangePlan,
  type IndexDepth,
  type IndexConfig,
  readBias,
  type BiasEdge,
  type BiasTarget,
  type BiasSign,
  particleBindings,
  deixisTable,
  particleMix,
  particleMixTotal,
  type ParticleBinding,
  type ParticleMix,
  resolveFragment,
  type ResolvedFragment,
  planSemanticEdits,
  applySemanticPlan,
  renameMark,
  renameParticle,
  type SemanticRule,
  type SemanticRewrite,
  type SemanticEdit,
  type SemanticConflict,
  type SemanticPlan,
  type SemanticPlanOptions,
  deriveMark,
  countOps,
  latestTimestamp,
  type MarkDeriver,
  type DeriveContext,
} from './canonical'

// NL preview
export { previewAST } from './instrumentation/preview'

// Math probes (graphs, loops, equations)
export {
  graphFromEdges,
  adjacencyList,
  adjacencyMatrix,
  detectCycle,
  topologicalSort,
  walkGraph,
  shortestPath,
  fixedPoint,
  boundedWhile,
  rangeFold,
  orbit,
  detectPeriod,
  logisticOrbit,
  evalPolynomial,
  residual,
  bisectionRoot,
  solveLinearSystem,
  productConstraint,
  linearResidual,
  cosineSimilarity,
  zeros,
  cloneField,
  fieldNorm,
  fieldSum,
  decayField,
  halfLifeToRate,
  diffuseField,
  transfer,
  flux,
  cascadeChain,
  capacityStep,
  affinityAllocate,
  mixFields,
  fieldBeat,
  massConserved,
  graphFromLinks,
  degreeHubs,
  topoLayers,
  analyzeTopography,
  compareFamiliarity,
  heuristicSigilHistogram,
  heuristicFrameCount,
  heuristicAnnotationHints,
  CORPUS_PRODUCT_VERSION,
  CORPUS_PRODUCT_SCHEMA,
  topSigils,
  populationRoleOf,
  buildPopulation,
  populationStats,
  sortPopulation,
  filterPopulation,
  buildCorpusProduct,
  FORMULA_CATALOG,
  scanFormulas,
  summarizeFormulaHits,
  aggregateFormulaPatterns,
  SPW_MATH_IDIOMS,
  idiomsForFamily,
  formatMathIdioms,
  type DirectedGraph,
  type GraphEdge,
  type CycleReport,
  type FixedPointResult,
  type FieldState,
  type Carrier,
  type BindingSite,
  type CorpusLink,
  type CorpusFileSignals,
  type TopographyReport,
  type FamiliarityCompare,
  type FamiliarityStrand,
  type HubScore,
  type PopulationRole,
  type PopulationRow,
  type PopulationStats,
  type CorpusProduct,
  type FormulaFamily,
  type FormulaHit,
  type FormulaCatalogEntry,
  type MathFamily,
  type SpwMathIdiom,
} from './math'

// Workspace contracts
export {
  analyzeWorkspaceRootManifest,
  parseWorkspaceRootDeclarations,
  type WorkspaceRootDeclaration,
  type WorkspaceRootManifestAnalysis,
  type WorkspaceRootManifestDiagnostic,
  type WorkspaceRootManifestDiagnosticCode,
} from './workspace-roots'

// Derived surface + gen-root conventions
export {
  DERIVED_SPW_KINDS,
  type DerivedSpwKind,
  isDerivedSurface,
  sourceSurfaceOf,
  derivedSurfaceName,
  SPW_GEN_ROOT,
  SPW_GEN_KINDS,
  type SpwGenKind,
  isGenPath,
  genSurfacePath,
  shouldSkipCorpusSurface,
} from './derived-surface'

// Sugar/desugar helpers
export { desugar, parseDesugared, normalizeToONF, type DesugarResult, type ONFNode, type FrameMap } from './normalize'
export {
  PAIRED_BOUNDARY_KINDS,
  COUPLING_DESCRIPTORS,
  couplingFrame,
  withCoupling,
  occupancyFromArgs,
  classifyPayload,
  couplingDescriptor,
  boundaryCoordinateForSurface,
  boundarySetForProfile,
  validateCouplingSemanticsProfile,
  projectCouplingSemantics,
  isBoundaryCouplingFrame,
  readCouplingFrame,
} from './types/coupling'
// Dialect + multi-axis surface profile stack
export type {
  DialectId,
  DialectSource,
  DialectDetection,
  ReviewProfileId,
  FormatProfileId as SurfaceFormatProfileId,
  MutationFamilyId,
  ReadingProfileId,
  DomainPackId,
  SurfaceProfileStack,
  MetasyntaxFlags,
  ResolveProfileOptions,
} from './dialect'
export {
  DEFAULT_DIALECT,
  DIALECT_IDS,
  detectDialect,
  isDialectId,
  applyDialectPreprocess,
  resolveSurfaceProfile,
  detectReviewProfile,
  detectDialectFromPath,
  collectMachineLintWarnings,
} from './dialect'

// Intermediate IR spine (interconnect, lenses, measure slices)
export {
  IR_KINDS,
  IR_EDGE_KINDS,
  irRef,
  irRefKey,
  asContentHash,
  asRequestEpoch,
  asSessionBeat,
  asProducerSchema,
  type ContentHash,
  type RequestEpoch,
  type SessionBeat,
  type ProducerSchema,
  type IrRefKeyParts,
  makeLens,
  openOptChannel,
  DEFAULT_OPT_CHANNELS,
  emptyInterconnect,
  putNode,
  link,
  neighbors,
  enableOpt,
  pushEffect,
  interconnectSummary,
  buildSurfaceInterconnect,
  resolveGranularity,
  grainWantsResonance,
  grainWantsEval,
  grainWantsInterconnect,
  formatGranularityAsSpw,
  type IrKind,
  type IrEdgeKind,
  type IrRef,
  type IrLens,
  type IrChannelId,
  type OptChannel,
  type TraversalEffect,
  type InterconnectGraph,
  type SelectionIR,
  type StackIR,
  type FormIR,
  type GraphIR,
  type AttentionIR,
  type MeasureIR,
  type StreamIR,
  type CacheIR,
  type EnvelopeMeta,
  type SurfaceCardIR,
  type Granularity,
  type GranularityDepth,
  type GranularityPlane,
  type GranularityFollow,
  type GranularityDisclose,
  type ResolveGranularityInput,
  PROGRESSIVE_PRODUCT_SURFACE,
  buildProgressiveProduct,
  type ProgressiveProductStatus,
  type ProgressiveProductSequence,
  type ProgressiveProductCompleteness,
  type ProgressiveProductRecord,
  type BuildProgressiveProductInput,
  CACHE_LAYER_SURFACE,
  CACHE_PLANES,
  CACHE_LAYER_DEFAULTS,
  assembleCacheLayers,
  formatCacheLayerLines,
  omitCacheLayer,
  presentCacheLayer,
  type CachePlane,
  type CacheLayerCard,
  type CacheLayerStats,
} from './ir'

// Experimental syntax catalog (plan/runtime reference ids)
export type {
  ExpRuntimeHook,
  ExpStatus,
  SyntaxCatalogEntry,
  ScannedExpRef,
  ExperimentalScan,
} from './experimental'
export {
  SYNTAX_CATALOG,
  getSyntaxCatalogEntry,
  listSyntaxCatalog,
  formatCatalogEntryMarkdown,
  scanExperimentalRefs,
  resolveCitedCatalogEntries,
} from './experimental'

// Query (spw.q dialect)
export type {
  SpwPattern,
  SpwSelector,
  SpwMatch,
  SpwMatchParticipant,
  SpwMatchEvidence,
  SpwMatchSpan,
  SpwTermSlotCoordinate,
  SpwSequenceSeparator,
  SigilSelector,
  BraceSelector,
  BoundarySelector,
  AttachedBoundarySelector,
} from './query'

export {
  spwq,
  matchAll,
  matchAt,
  and,
  or,
  not,
  descend,
  seq,
  anyNode,
  capture,
  assertSpwSelector,
  isSpwSelector,
  PATH_REFS,
  REFERENCES,
  NAVIGABLE,
  DOMAIN_ROOTS,
  DOMAIN_ROOTS_FULL,
  HYDRATE_OPS,
  DEFER_OPS,
  QUERY_OPS,
  CONFIG_OPS,
  BIAS,
  PARTICLES,
  ANCHORS,
  ANNOTATION_OPS,
  OPS_WITH_FRAMES,
  OPS_WITH_BODIES,
  SCOPES,
  BOON_OPS,
  BONE_OPS,
  ANY,
} from './query'

export {
  parseSelector,
  tryParseSelector,
  SelectorParseError,
} from './query/selector-expr'

export {
  MEDIAL_CAPSULE_CHANNELS,
  VALENCE_PARTICLES,
  TEMPLATE_SLOTS,
  SIGIL_SNIPPET_CATALOG,
  type MedialChannelDef,
  type ValenceParticleDef,
  type TemplateSlotDef,
  type SigilSnippetDef,
} from './canonical'
