/**
 * Spw Parser
 *
 * A generator-based parser for the Spw language.
 * All parsing operations yield ParseEvent objects for unified logging and debugging.
 *
 * @spw:portable:seed - No DOM or app-specific imports allowed
 */

// Core types
export type {
  Position,
  Span,
  Brand,
  Token,
  TokenType,
  OperatorKind,
  ModifierKind,
  ConnectorKind,
  ContainerKind,
  CouplingKind,
  PairedBoundaryKind,
  CouplingForm,
  BoundarySide,
  CouplingOccupancy,
  CouplingPayload,
  ActPlacement,
  OperatorCouplingPort,
  BoundaryCouplingPort,
  CouplingPort,
  CouplingDescriptor,
  OperatorCouplingDescriptor,
  BoundaryCouplingDescriptor,
  CouplingFrame,
  OperatorCouplingFrame,
  BoundaryCouplingFrame,
  BoundarySurfaceCoordinate,
  CouplingProfileStatus,
  CouplingDimensionValueType,
  CouplingDimensionDefinition,
  CouplingPortSemantics,
  CouplingDynamicsDefinition,
  CouplingKindSemantics,
  CouplingSemanticsProfile,
  CouplingProfileIssue,
  CouplingSemanticsProjection,
  ParseEvent,
  ParseEventType,
  TokenEventData,
  EnterEventData,
  ExitEventData,
  MatchEventData,
  BacktrackEventData,
  ErrorEventData,
  ASTNode,
  ASTNodeType,
  SeedNode,
  ExpressionNode,
  OperationNode,
  ModifierChainNode,
  ScopeNode,
  FrameNode,
  BodyNode,
  SequenceNode,
  ReferenceNode,
  LiteralNode,
  IdentifierNode,
  AnnotationNode,
  ConditionNode,
  ParameterNode,
  ProseNode,
  ProseChunkNode,
  CapsuleNode,
  StreamNode,
  NRangeNode,
  MatchNode,
  MatchArmNode,
  WildcardNode,
  SpreadNode,
  PatternNode,
  ParseGenerator,
  ParseResult,
  ParseContextMode,
  ParserOptions,
  LexProfile,
  LexOptions,
} from './types'

export { DEFAULT_OPTIONS } from './types'
export { castToBrand, $register, $frame, $domain, $layer, RegisterId, FrameId, DomainId, LayerId } from './types'

// Lexer
export {
  lex,
  tokenize,
  DEFAULT_LEX_PROFILE,
  PROSE_LEX_PROFILE,
  registerLexProfile,
  resolveLexProfile,
  getLexProfile,
  listLexProfiles,
  buildOperatorMap,
  buildConnectorMap,
} from './lexer'

// Combinators
export type { TokenStream, Parser } from './combinators'
export {
  createTokenStream,
  sequence,
  choice,
  many,
  many1,
  optional,
  map,
  sepBy,
  between,
  lazy,
  named,
  token,
} from './combinators'

// Grammar
export {
  seedNode,
  expressionNode,
  operationNode,
  scopeNode,
  frameNode,
  bodyNode,
  sequenceNode,
  referenceNode,
  literalNode,
  annotationNode,
  modifierChain,
  parameterNode,
} from './grammar'

// Parser
export type { ParseOutput, LogFormatter, TraceNode } from './parser'
export {
  parse,
  parseExpression,
  parseStream,
  parseWithLog,
  textFormatter,
  jsonFormatter,
  compactFormatter,
  filterEvents,
  extractTokens,
  extractErrors,
  buildTrace,
  printAST,
} from './parser'

// Instrumentation
export type {
  InstrumentationHooks,
  ASTVisitor,
  AuditItem,
  ASTAuditResult,
  RuleCoverage,
  CoverageReport,
  TimingMetrics,
  RuleTiming,
  EventFilter,
  EventSubscriber,
} from './instrumentation'

export {
  noopHooks,
  createHooks,
  combineHooks,
  processEvent,
  walkAST,
  getNodeChildren,
  findNodes,
  getNodePath,
  getMaxDepth,
  countNodeTypes,
  auditAST,
  CoverageCollector,
  createCoverageHooks,
  MetricsCollector,
  createMetricsHooks,
  EventStream,
  eventFilters,
  createStreamHooks,
} from './instrumentation'

// Canonicalization, differentials, mutation automata, topography probes
export {
  canonicalize,
  hashString,
  applyEdits,
  differentialFromSources,
  runMutationAutomata,
  planMutation,
  collectPlannedEdits,
  resolveMutationRules,
  BUILTIN_MUTATION_RULES,
  MUTATION_PROFILES,
  applyEquivScriptTransforms,
  mutationRulesAsSequenceContext,
  probeMutationTopography,
  snapshotTopography,
  topographyDelta,
  transformEdit,
  transformEditList,
  foldEdits,
  foldTransforms,
  composeEditLists,
  composeSequence,
  matrixFromVectors,
  matrixByStratum,
  formatMatrix,
  vectorMagnitude,
  runOperationalSequence,
  OPERATIONAL_SEQUENCES,
  BOUNDARY_LADDERS,
  OPERATOR_LADDERS,
  BOUNDARY_AXIS_IMPLICATIONS,
  FORM_LADDER_PROFILE,
  boundaryLadder,
  operatorLadder,
  listBoundaryLadders,
  listOperatorLadders,
  listFormLadders,
  probeBoundaryLadder,
  probeOperatorLadder,
  resolveLadderQuery,
  formatBoundaryAxisTable,
  formatAllLadderNotations,
  operatorLadderTable,
  boundaryLadderTable,
  implicationsForBoundary,
  MOBILITY_RULES,
  REFERENCE_PROGRESSIONS,
  HIGHER_ORDER_FORMS,
  applyMobilityRule,
  walkReferenceProgression,
  runHigherOrderForm,
  formatSiteGraph,
  formatHigherOrderForms,
  formatMobilityRules,
  computationalRuleIds,
  labelSiteGraph,
  type CanonicalOptions,
  type CanonicalResult,
  type SourceEdit,
  type SourceDifferential,
  type MutationVector,
  type MutationAutomataConfig,
  type MutationRunResult,
  type MutationProfileId,
  type MutationRule,
  type EffectGrade,
  type TopographySnapshot,
  type TopographyDelta,
  type TopographyMutationProbe,
  type ParseHealth,
  type PairedContainerCounts,
  type MutationMatrix,
  type OperationalSequence,
  type SequenceRunResult,
  type OperatorLadder,
  type ResolvedFormLadder,
  type BoundaryLadder,
  type FormLadder,
  type FormLadderProbe,
  type OperatorLadderProbe,
  type EnrichmentRole,
  type LadderStep,
  type FormAxis,
  type BoundaryLadderId,
  type LabelSite,
  type LiminalShape,
  type MobilityRule,
  type HigherOrderForm,
  type ReferenceProgression,
  type LabelPosition,
} from './canonical'

// NL preview
export { previewAST } from './instrumentation/preview'

// Workspace contracts
export {
  parseWorkspaceRootDeclarations,
  type WorkspaceRootDeclaration,
} from './workspace-roots'

// Sugar/desugar helpers
export { desugar, parseDesugared, normalizeToONF, type DesugarResult, type ONFNode, type FrameMap } from './normalize'
export {
  COUPLING_DESCRIPTORS,
  couplingFrame,
  withCoupling,
  occupancyFromArgs,
  classifyPayload,
  couplingDescriptor,
  boundaryCoordinateForSurface,
  boundarySetForProfile,
  validateCouplingSemanticsProfile,
  projectCouplingSemantics,
  isBoundaryCouplingFrame,
  readCouplingFrame,
} from './types/coupling'
// Query (spw.q dialect)
export type {
  SpwPattern,
  SpwSelector,
  SpwMatch,
  SpwMatchSpan,
  SigilSelector,
  BraceSelector,
} from './query'

export {
  spwq,
  matchAll,
  matchAt,
  and,
  or,
  not,
  descend,
  seq,
  PATH_REFS,
  REFERENCES,
  NAVIGABLE,
  DOMAIN_ROOTS,
  DOMAIN_ROOTS_FULL,
  HYDRATE_OPS,
  DEFER_OPS,
  QUERY_OPS,
  CONFIG_OPS,
  ANNOTATION_OPS,
  OPS_WITH_FRAMES,
  OPS_WITH_BODIES,
  SCOPES,
  BOON_OPS,
  BONE_OPS,
  ANY,
} from './query'

export {
  parseSelector,
  tryParseSelector,
  SelectorParseError,
} from './query/selector-expr'
