/**
 * Canonicalization, source differentials, and mutation automata.
 *
 * @see docs/theory/spw/operational-topography.spw
 * @see docs/theory/spw/mutation-automata.spw
 */

export {
  canonicalize,
  hashString,
  type CanonicalOptions,
  type CanonicalResult,
} from './canonicalize'

export {
  applyEdits,
  differentialFromSources,
  effectGradeAtMost,
  mergeVectors,
  zeroVector,
  EFFECT_GRADE_ORDER,
  type DifferentialStratum,
  type EffectGrade,
  type MutationVector,
  type SourceDifferential,
  type SourceEdit,
} from './differential'

export {
  BUILTIN_MUTATION_RULES,
  MUTATION_PROFILES,
  applyEquivScriptTransforms,
  collectPlannedEdits,
  planMutation,
  planMutationPass,
  planRuleDifferential,
  resolveMutationRules,
  runMutationAutomata,
  type MutationAutomataConfig,
  type MutationContext,
  type MutationProfileId,
  type MutationRule,
  type MutationRunResult,
  type MutationStep,
  type MutationStopReason,
} from './mutation-automata'

export {
  probeMutationTopography,
  snapshotTopography,
  topographyDelta,
  type PairedContainerCounts,
  type ParseHealth,
  type TopographyDelta,
  type TopographyMutationProbe,
  type TopographySnapshot,
} from './topography-probe'

export {
  transformEdit,
  transformEditList,
  foldEdits,
  foldTransforms,
  composeEditLists,
  composeSequence,
  editLengthDelta,
  vectorToArray,
  vectorFromArray,
  scaleVector,
  dotVectors,
  vectorMagnitude,
  matrixFromVectors,
  matrixByStratum,
  matrixAdd,
  matrixVectorMul,
  matrixTranspose,
  formatMatrix,
  runOperationalSequence,
  sequenceContextFromMap,
  emptySequenceContext,
  OPERATIONAL_SEQUENCES,
  MUTATION_VECTOR_AXES,
  STRATUM_ORDER,
  type TransformResult,
  type TransformConflict,
  type MutationMatrix,
  type MutationVectorAxis,
  type SequenceStep,
  type SequenceStepKind,
  type OperationalSequence,
  type SequenceRunResult,
  type ResolveStepContext,
} from './operational-transform'

export { mutationRulesAsSequenceContext } from './mutation-automata'

export {
  BOUNDARY_LADDERS,
  OPERATOR_LADDERS,
  BOUNDARY_AXIS_IMPLICATIONS,
  FORM_LADDER_PROFILE,
  boundaryLadder,
  operatorLadder,
  listBoundaryLadders,
  listOperatorLadders,
  listFormLadders,
  implicationsForBoundary,
  implicationsForAxis,
  probeBoundaryLadder,
  probeOperatorLadder,
  resolveLadderQuery,
  formatBoundaryAxisTable,
  formatAllLadderNotations,
  operatorLadderTable,
  boundaryLadderTable,
  type EnrichmentRole,
  type LadderStep,
  type FormLadder,
  type BoundaryLadder,
  type OperatorLadder,
  type ResolvedFormLadder,
  type FormAxis,
  type BoundaryLadderId,
  type FormLadderProbe,
  type OperatorLadderProbe,
  type LadderStepProbe,
  type BoundaryAxisImplication,
  type LadderArrow,
} from './form-ladders'

export {
  MOBILITY_RULES,
  REFERENCE_PROGRESSIONS,
  HIGHER_ORDER_FORMS,
  REGISTER_LIMINALITY_ORDER,
  LIMINAL_SHAPE_TO_REGISTER,
  mobilityRule,
  rulesFrom,
  rulesTo,
  rulesByMotion,
  rulesByStatus,
  applyMobilityRule,
  walkReferenceProgression,
  runHigherOrderForm,
  labelSiteGraph,
  formatSiteGraph,
  formatHigherOrderForms,
  formatMobilityRules,
  computationalRuleIds,
  type LabelSite,
  type LiminalShape,
  type RegisterLiminality,
  type LabelPosition,
  type LabelPositionPattern,
  type MobilityRule,
  type RuleStatus,
  type ReferenceProgression,
  type HigherOrderForm,
  type SiteEdge,
} from './form-geometry'
